/**
 * Which state transitions a work row may offer.
 *
 * This module used to be about focus TARGETS: the badge that read "6 / 5", the
 * question asked when activating would cross the number, how long somebody had
 * been over it, and which work classes counted towards it at all. The Manager
 * and Employee Change Specification removes all of that — §3 because the
 * ratios are not reliable workload measures, and §11 because the enforcement
 * built on them contradicts the guidance that replaces it. v144 took the
 * display, the question, the manager notification and the database gate
 * together, since keeping any one of them would have left the product still
 * arguing from a number it had stopped believing.
 *
 * What survives is the part that was never about capacity: whether a row is in
 * a state where Activate or Move out means anything. The database remains
 * authoritative for whether the operation is permitted; these two answer the
 * narrower question of which control to draw.
 */

import type { TaskStatus, WorkClass } from './types';

/**
 * Whether Activate should be offered at all.
 *
 * Only the state matters. It never depended on how much somebody was already
 * carrying — that was the whole point of a soft target, and there is no target
 * left to be soft about.
 */
export function canOfferActivate(status: TaskStatus, workClass?: WorkClass): boolean {
  /*
   * A routine occurrence is never activated.
   *
   * It is generated by a schedule, it is due or it is upcoming, and there is
   * no decision to take about carrying it. Offering Activate on one asked a
   * question the routine model does not have, and the "Available" beside it
   * named a state an occurrence is never really in.
   *
   * The work class is optional because most callers already know they are
   * looking at Focus work; where it is passed, it is the authority.
   */
  if (workClass === 'routine_occurrence') return false;
  return status === 'backlog' || status === 'paused';
}

/** Section 7.5 — Active work offers a quiet secondary move-out action. */
export function canOfferMoveOut(status: TaskStatus): boolean {
  return status === 'active';
}
