import { describe, expect, it } from 'vitest';

import { canOfferActivate, canOfferMoveOut } from '@/domain/focus';

/**
 * This file used to be mostly about the focus target: the "6 / 5" badge, the
 * six approved reasons for crossing it, the wording of the one question, and
 * how long somebody had been over. v144 removed the target from the product
 * (specification §3, §11) and those tests went with the code they described —
 * a test asserting the exact phrasing of a question nobody is asked any more
 * is not coverage, it is a fossil that fails the day somebody tidies up.
 *
 * What is left is the rule that never depended on capacity: which control a
 * row offers, decided by its state.
 */

describe('which control a row offers', () => {
  it('offers Activate for Available Work', () => {
    expect(canOfferActivate('backlog')).toBe(true);
  });

  it('offers Activate for paused work', () => {
    expect(canOfferActivate('paused')).toBe(true);
  });

  it('does not offer Activate for work that is already Active', () => {
    expect(canOfferActivate('active')).toBe(false);
  });

  /*
   * A routine occurrence is generated by a schedule. It is due or it is
   * upcoming, and "activating" it names a state it is never in.
   */
  it('never offers Activate on a routine occurrence, whatever its state', () => {
    expect(canOfferActivate('backlog', 'routine_occurrence')).toBe(false);
    expect(canOfferActivate('paused', 'routine_occurrence')).toBe(false);
  });

  it('offers Move out only for Active work', () => {
    expect(canOfferMoveOut('active')).toBe(true);
    expect(canOfferMoveOut('backlog')).toBe(false);
  });
});
